# Kubernetes Secret resource for Detection Translation Platform
# Version: v1
# Purpose: Stores sensitive configuration data and credentials for platform services
# Security: Data is base64 encoded and encrypted at rest using AES-256-GCM
# Auto-rotation: Enabled with 30-day rotation interval

apiVersion: v1
kind: Secret
metadata:
  name: detection-platform-secrets
  namespace: detection-platform
  labels:
    app.kubernetes.io/name: detection-platform
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: detection-translation-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    kubernetes.io/created-by: detection-platform-admin
    secret.kubernetes.io/auto-rotation: enabled
    secret.kubernetes.io/rotation-interval: "720h"
type: Opaque
data:
  # API Gateway Service Credentials
  # Used for authentication, caching, messaging, and GitHub integration
  api-gateway.JWT_SECRET: ${JWT_SECRET}
  api-gateway.AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  api-gateway.AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
  api-gateway.AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
  api-gateway.REDIS_HOST: ${API_REDIS_HOST}
  api-gateway.REDIS_PORT: ${API_REDIS_PORT}
  api-gateway.REDIS_PASSWORD: ${API_REDIS_PASSWORD}
  api-gateway.RABBITMQ_HOST: ${API_RABBITMQ_HOST}
  api-gateway.RABBITMQ_PORT: ${API_RABBITMQ_PORT}
  api-gateway.RABBITMQ_USERNAME: ${API_RABBITMQ_USERNAME}
  api-gateway.RABBITMQ_PASSWORD: ${API_RABBITMQ_PASSWORD}
  api-gateway.GITHUB_APP_ID: ${GITHUB_APP_ID}
  api-gateway.GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
  api-gateway.GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

  # Translation Service Credentials
  # Used for AI model access, database connectivity, caching, and messaging
  translation-service.OPENAI_API_KEY: ${OPENAI_API_KEY}
  translation-service.OPENAI_ORG_ID: ${OPENAI_ORG_ID}
  translation-service.MONGODB_URI: ${TRANS_MONGODB_URI}
  translation-service.MONGODB_USERNAME: ${TRANS_MONGODB_USERNAME}
  translation-service.MONGODB_PASSWORD: ${TRANS_MONGODB_PASSWORD}
  translation-service.REDIS_HOST: ${TRANS_REDIS_HOST}
  translation-service.REDIS_PORT: ${TRANS_REDIS_PORT}
  translation-service.REDIS_PASSWORD: ${TRANS_REDIS_PASSWORD}
  translation-service.RABBITMQ_HOST: ${TRANS_RABBITMQ_HOST}
  translation-service.RABBITMQ_PORT: ${TRANS_RABBITMQ_PORT}
  translation-service.RABBITMQ_USERNAME: ${TRANS_RABBITMQ_USERNAME}
  translation-service.RABBITMQ_PASSWORD: ${TRANS_RABBITMQ_PASSWORD}
  translation-service.MODEL_ENCRYPTION_KEY: ${MODEL_ENCRYPTION_KEY}

  # Validation Service Credentials
  # Used for database access, caching, and service authentication
  validation-service.MONGODB_URI: ${VAL_MONGODB_URI}
  validation-service.MONGODB_USERNAME: ${VAL_MONGODB_USERNAME}
  validation-service.MONGODB_PASSWORD: ${VAL_MONGODB_PASSWORD}
  validation-service.REDIS_HOST: ${VAL_REDIS_HOST}
  validation-service.REDIS_PORT: ${VAL_REDIS_PORT}
  validation-service.REDIS_PASSWORD: ${VAL_REDIS_PASSWORD}
  validation-service.SERVICE_API_KEY: ${VAL_SERVICE_API_KEY}
  validation-service.VALIDATION_ENCRYPTION_KEY: ${VAL_ENCRYPTION_KEY}