# ServiceAccount configuration for Detection Translation Platform
# Implements secure pod authentication and RBAC integration with enhanced security controls
# Version: v1.0.0

---
# API Gateway Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: detection-platform
  labels:
    app: api-gateway
    component: gateway
    managed-by: terraform
    security-tier: critical
    compliance: soc2
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform/token-rotation: "enabled"
    security.platform/audit-logging: "enabled"
    security.platform/access-review: "required"
automountServiceAccountToken: true

---
# Translation Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: translation-service-sa
  namespace: detection-platform
  labels:
    app: translation-service
    component: translation
    managed-by: terraform
    security-tier: critical
    compliance: soc2
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform/token-rotation: "enabled"
    security.platform/audit-logging: "enabled"
    security.platform/access-review: "required"
automountServiceAccountToken: true

---
# Validation Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validation-service-sa
  namespace: detection-platform
  labels:
    app: validation-service
    component: validation
    managed-by: terraform
    security-tier: critical
    compliance: soc2
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform/token-rotation: "enabled"
    security.platform/audit-logging: "enabled"
    security.platform/access-review: "required"
automountServiceAccountToken: true

---
# Monitoring Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
  labels:
    app: monitoring
    component: observability
    managed-by: terraform
    security-tier: high
    compliance: soc2
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform/token-rotation: "enabled"
    security.platform/audit-logging: "enabled"
    security.platform/metrics-collection: "enabled"
automountServiceAccountToken: true