# Translation Service Deployment Manifest
# Base Image: python:3.11-slim
# Purpose: Manages the Translation Service pods responsible for detection format conversion
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
  namespace: detection-platform
  labels:
    app.kubernetes.io/name: translation-service
    app.kubernetes.io/component: translation
    app.kubernetes.io/part-of: detection-platform
    app.kubernetes.io/version: "1.0.0"
spec:
  # High availability configuration with 3 replicas
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: translation-service
  # Rolling update strategy to ensure zero-downtime deployments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: translation-service
        app.kubernetes.io/component: translation
        app.kubernetes.io/part-of: detection-platform
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      # Service account for pod authentication
      serviceAccountName: translation-service-sa
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: translation-service
          image: translation-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8080
              name: metrics
          # Resource limits as per container specifications
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          # Container-level security context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          # Configuration and secrets mounting
          envFrom:
            - configMapRef:
                name: translation-service-config
            - secretRef:
                name: translation-service-secrets
      # Pod anti-affinity for high availability
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: translation-service
                topologyKey: kubernetes.io/hostname